### ISSUE TITLE
Wrong version in marketplace

### ISSUE THREAD

**Issue by luiszimmermann** [reviewdog/action-stylelint#27]
Only 1.0.0 and 1.0.1 are in the [marketplace](https://github.com/marketplace/actions/run-stylelint-with-reviewdog). I saw the same with the eslint action.

![image](https://user-images.githubusercontent.com/17937861/102530287-d85e1200-407f-11eb-9d91-9b40d65befac.png)

**Comment by shogo82148** [comment]
This problem exists not only for stylint and eslint, but also for all actions on the reviewdog org.
Because the actions are based on https://github.com/reviewdog/action-template, and action-template has same problem.

please report to https://github.com/reviewdog/action-template/issues/11 if you have any information.
it helps that we resolve problems of the actions the reviewdog org.

**Comment by shogo82148** [comment]
I updated the latest version v1.17.0

<img width="354" alt="image" src="https://github.com/reviewdog/action-stylelint/assets/1157344/10e4ee5a-3d4b-4e94-83ac-aff31c49cb24">
